
# mysql docker container configuration
mysql:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/${MYSQL_DB_NAME}
    username: ${MYSQL_DB_USER_NAME}
    password: ${MYSQL_DB_PASS}


# Postgres docker container configuration
postgres:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5484/${POSTGRES_DB_NAME}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASS}


management:
  endpoints:
    web:
      exposure:
        include: health,info,env

  endpoint:
    health:
      show-details: always