
mysql:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/mydb
    username: myuser
    password: mypassword

postgres:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgresdb
    username: postgres
    password: postgres
