mysql:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/gowtham_db
    username: gowtham_dev_user1
    password: todayFestival@26

postgres:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5484/gowtham_postgresdb
    username: gowtham_dev_user2
    password: todayFestival@269


management:
  endpoints:
    web:
      exposure:
        include: health,info,env

  endpoint:
    health:
      show-details: always


